#Config for connecting to service-discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      #      The &{EUREKA_SERVER_ADDRESS} is when env variable is present, if not then use the localhost url
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
