#Config for connecting to service-discovery
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      # The &{EUREKA_SERVER_ADDRESS} is when env variable is present, if not then use the localhost url
okta:
  oauth2:
    issuer: https://dev-37484179.okta.com/oauth2/default
    audience: api://default
